### ISSUE TITLE
Timer not started if first move is wrong move.

### ISSUE THREAD

**Issue by web3devz** [gameric/8-puzzle#24]
Hello sir,
the timer of this game is not counted if the first move is wrong move then the timer stay at 1sec.
please check and correct it.

**Comment by kerolloz** [comment]
Thank you for reporting this bug 🐞.
Fixed it ✅ on [this](https://github.com/gameric/8-puzzle/commit/cd0f65f7a61ed3dcb0dcbfbdf5167f778f822d32#diff-992d2cbf1fff1604e234506cac561197fef6c1d37cea82184cb84f9fb3a91826L78-L95) commit.
https://8-puzzle.pages.dev/
